variable "region" {}
variable "ami" {}
variable "instance_type" {}
variable "key" {}
variable "cidr_blocks" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
variable "availability_zone" {}
variable "protocol" {}
variable "key_path" {}
